--CREATE DATABASE softwareplant;
--CREATE TABLE reports (
--    report_id BIGINT AUTOINCREMENT PRIMARY_KEY,
--    query_criteria_character_phrase VARCHAR(255),
--    query_criteria_planet_name VARCHAR(255),
--    film_id VARCHAR(255), film_name, character_id,
--character_name, planet_id, planet_name.
--)
--
